"""UDP受信処理で利用する定数を定義するモジュール。"""

RECEIVE_MULTICAST_IP = "239.192.0.2"
RECEIVE_BIND_IP = "0.0.0.0"
# マルチキャスト参加時に利用する受信インターフェースIP。
RECEIVE_INTERFACE_IP = "10.0.0.10"
RECEIVE_PORT = 60002
RECEIVE_BUFFER_SIZE = 4096
RECEIVE_SOCKET_TIMEOUT_SECONDS = 1.0

# 連続運転時に次サイクル開始まで待機する秒数。
RECEIVE_CYCLE_RESTART_DELAY_SECONDS = 5
