"""TDBセンテンス処理に関する定数を定義する。"""

NMEA_SENTENCE_START_MARK = "!"
NMEA_FIELD_SEPARATOR = ","
NMEA_CHECKSUM_SEPARATOR = "*"

TDB_TOKEN_LENGTH = 5
TDB_TOKEN_SUFFIX = "TDB"
TDB_MIN_FIELD_COUNT = 10
TDB_GROUP_IDENTITY_MIN_FIELD_COUNT = 6

TDB_FIELD_TOTAL_POSITION = 1
TDB_FIELD_SEGMENT_INDEX_POSITION = 2
TDB_FIELD_SEQUENCE_POSITION = 3
TDB_FIELD_SOURCE_POSITION = 4
TDB_FIELD_DESTINATION_POSITION = 5
TDB_FIELD_PAYLOAD_POSITION = 8
TDB_FIELD_FILL_POSITION = 9

TDB_FILL_MIN_VALUE = 0
TDB_FILL_MAX_VALUE = 5

TDB_GROUP_EXPIRY_SECONDS = 30

AIS_SIXBIT_CHUNK_SIZE = 6
AIS_SIXBIT_MIN_VALUE = 0
AIS_SIXBIT_MAX_VALUE = 63
AIS_CHAR_SPLIT_THRESHOLD = 40

AIS_CHAR_RANGE_LOW_START = 48
AIS_CHAR_RANGE_LOW_END = 87
AIS_CHAR_RANGE_HIGH_START = 96
AIS_CHAR_RANGE_HIGH_END = 119
AIS_CHAR_LOW_OFFSET = 48
AIS_CHAR_HIGH_OFFSET = 56
